spring:
    datasource:
        url: jdbc:mysql://localhost:3306/trello
        password: root  
        username: root
    jpa:
        hibernate:            
            database-platform: org.hibernate.dialect.H2Dialect
            #show-sql: true
            #ddl-auto: create-drop
    redis:
        host: localhost
        port=6379
    mail:
        host: smtp.gmail.com
        port: 587
        fromEmail: duong2lophot@gmail.com
        password:  adfadfdfd

