server:
    port: 5000
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/trello?allowPublicKeyRetrieval=true&useSSL=false
        password: root  
        username: root
    jpa:
        hibernate:            
            database-platform: org.hibernate.dialect.H2Dialect
            show-sql: true
            ddl-auto: update
    redis:
        host: localhost
        port: 6379
    mail:
        host: smtp.gmail.com
        port: 587
        fromEmail: duong2lophot@gmail.com
        password:  adfadfdfd
    minio:
        url: http://127.0.0.1:9000
        access-key: your-access-key
        secret-key: your-secret-key
        bucket-name: testbucket


