version: "3.1"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - connect

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - connect

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - connect
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123456aA@
    command: server /data --console-address ":9001"
    
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbit
    ports:
      - "5672:5672" # Default RabbitMQ port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

networks:
  connect:
    driver: bridge

volumes:
  db_data:
  redis_data:
  redis-insight:
  minio_data:
  rabbitmq_data:
